INSERT INTO PRODUCT(PRODUCT_NAME, PRODUCT_PRICE) VALUES('Latte', 5.3);
INSERT INTO PRODUCT(PRODUCT_NAME, PRODUCT_PRICE) VALUES('Espresso', 4);
INSERT INTO PRODUCT(PRODUCT_NAME, PRODUCT_PRICE) VALUES('Sandwich', 10.10);
INSERT INTO PRODUCT(PRODUCT_NAME, PRODUCT_PRICE) VALUES('Milk', 1);
INSERT INTO PRODUCT(PRODUCT_NAME, PRODUCT_PRICE) VALUES('Cake Slice', 9);
INSERT INTO PRODUCT(PRODUCT_NAME, PRODUCT_PRICE) VALUES('Capuccino', 8);
INSERT INTO PRODUCT(PRODUCT_NAME, PRODUCT_PRICE) VALUES('Tea', 6.1);